### ISSUE TITLE
px-dropdown-min-width should not constrain the minimum width of dropdown triggers

### ISSUE THREAD

**Issue by evanjd** [predixdesignsystem/px-dropdown#101]
_Originally posted by @vincentcn in https://github.com/predixdesignsystem/px-dropdown/pull/96#pullrequestreview-205654871_

According to [the documentation](https://www.predix-ui.com/#/elements/px-dropdown),  it is used to specify min width for the dropdown menu container, right?
![dropdown_document](https://user-images.githubusercontent.com/443663/53080584-f4500580-3533-11e9-8997-ba6135a9c370.png)

When a dropdown is used as iconic menu, obviously it's not applicable to apply `--px-dropdown-min-width` as the min-width for dropdown-trigger since dropdown-trigger is an icon.
<img width="203" alt="iconicmenu" src="https://user-images.githubusercontent.com/443663/53081129-2ca41380-3535-11e9-8434-8861ef7f6682.png">

**Comment by evanjd** [comment]
@vincentcn Released 4.9.2 with this change.

**Comment by vincentcn** [comment]
See it, thanks.  Will upgrade it in our project.
