### ISSUE TITLE
single mode - no chevron

### ISSUE THREAD

**Issue by hlltarakci** [predixdesignsystem/px-dropdown#108]
Hi,
Since [it checks for length of selectedValues which is not available in single mode](https://github.com/predixdesignsystem/px-dropdown/blob/v4.9.3/px-dropdown-trigger.html#L252) , chevron is not shown in single mode.
Workaround: Adding selected-values='[]'  to the component fixes it.
Thanks..

**Comment by kmackinnon** [comment]
Are you able to recreate the problem using the [demo](https://www.predix-ui.com/#/elements/px-dropdown)?

**Comment by hlltarakci** [comment]
I copied demo file in my project env and tried that way, so it is kind of a dirty trial..
I wanted to open an issue anyway, in case the workaround helps with people similar with my case..
