### ISSUE TITLE
Enhancement: Select all functionality in checkbox/checkbox + search mode

### ISSUE THREAD

**Issue by brettjohns89** [predixdesignsystem/px-dropdown#44]
## Expected behavior:

It would be very useful to have the ability to have a "Select All" option for the dropdown component when using checkbox or checkbox + search mode. We have use cases where users would like to select a large number of items all at once 

## Steps to reproduce the problem:

Use the px-dropdown component and set it to checkbox mode

**Comment by randyaskin** [comment]
I'm working on this over at https://github.com/PredixDev/px-dropdown/tree/selectAll - added it to the API easy enough, but I need our designers to tell me where the affordance should be placed and how it should appear.

**Comment by yasemin-alpay** [comment]
Hi, are there still any plans for this?

**Comment by yasemin-alpay** [comment]
That is perfect! Thanks @sgoodrow

**Comment by arongraham-ge** [comment]
@yasemin-alpay how did you go with this feature update? It would be great to see it merged into the master branch. Let me know if you need any help

**Comment by surykumar** [comment]
Hi, is the selectAll feature going to add in dropdown?
