### ISSUE TITLE
highlighting does not adjust when order of items changes

### ISSUE THREAD

**Issue by ge-kosc** [predixdesignsystem/px-dropdown#64]
Expected behavior and actual behavior:

I would expect correct item to be marked as selected when selected item changes and order of item changes

## Steps to reproduce the problem:

Fill component with items and set one of them as selected. Change order of items and set other item as selected. Correct item is selected (cannot be selected by click) but it's previous position is highlighted instead of current one (when highlighted item is clicked then it becomes selected one).

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
component version: 4.0.18; 
system: Windows 7;
browser: Version 62.0.3202.75 (Official Build) (64-bit)

**Comment by randyaskin** [comment]
This is an issue within the underlying iron-selector component:
https://github.com/PolymerElements/iron-selector/issues/82
