### ISSUE TITLE
Support display selected values instead of "n selected" in multiple selection mode

### ISSUE THREAD

**Issue by vincentcn** [predixdesignsystem/px-dropdown#69]
# Support display selected values instead of "n selected" in multiple selection mode

Hi,

Currently px-dropdown component display "n selected" in multiple selection mode
![screen shot 2018-01-16 at 5 29 24 pm](https://user-images.githubusercontent.com/443663/34981685-333f8fcc-fae3-11e7-9dbf-ec887bb4f729.png)

Users have to make one click to view current selected values when px-dropdown is used as an input in a form. It is not good user experience. 
Could you please help to support display selected values like this:
![dropdownwithdisplayvalue](https://user-images.githubusercontent.com/443663/34981850-c0b84c22-fae3-11e7-8667-d5bf1bd2655b.png)

**Comment by randyaskin** [comment]
The comma-separated list was how the functionality was originally implemented in Piotrek's pull request, but it's not scalable from a usability perspective: https://github.com/PredixDev/px-dropdown/pull/32#issuecomment-287934449

**Comment by vincentcn** [comment]
A dropdown component does not have many selections in most cases. How about make it configurable, display "n selected" or comma separated list can be configured by a flag?

**Comment by arongraham-ge** [comment]
@vincentcn this has been added in release v4.8.0
