### ISSUE TITLE
px-dropdown is loading unused icons (making it less performant by making network round trips for unneeded resources)...

### ISSUE THREAD

**Issue by cherukumilli** [predixdesignsystem/px-dropdown#74]
## Expected behavior and actual behavior:
`px-dropdown` is only using icons with prefix `px-nav` and `px-utl`. It should only import `px-icon-set-navigation.html` and `px-icon-set-utility.html`. i.e., it should not import the rest of icon files.

## Steps to reproduce the problem:
1. Load a project that imports `px-dropdown` or go to https://www.predix-ui.com/#/elements/px-dropdown
2. Open google chrome developer tools
3. Go to the network tab
4. Refresh the page
5. filter on `px-icon-set-`
6. You will see that `px-dropdown` imports the following files

- px-icon-set-navigation.html
- px-icon-set-communication.html
- px-icon-set-document.html
- px-icon-set-feature.html
- px-icon-set-object.html
- px-icon-set-utility.html
- px-icon-set-vis.html

It should only be importing `px-icon-set-utility.html` and `px-icon-set-navigation.html`

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
`4.5.4`

## Screenshots (_optional, but very helpful_):

![screen shot 2018-02-10 at 1 58 54 pm](https://user-images.githubusercontent.com/5217007/36067061-99f2703c-0e6a-11e8-9836-83acf5c3ab05.png)

**Comment by randyaskin** [comment]
Valid point, and in a brief informal test using Chrome DevTools, it did have a meaningful impact on the performance of our simple_demo page. The only problem will be that we offer the `icon` property (both for the trigger and next to individual options in the list) so this would be an API-breaking change, as developers who are using custom icons from the other 5 icon sets will have to add an import for the corresponding file, and we'll have to document that well.

**Comment by arongraham-ge** [comment]
Closing as the breaking change to the API outweighs the impact on performance. Projects can fork px-dropdown and disable unwanted icon files if required
