### ISSUE TITLE
px-dropdown 4.5.4 and above not working in IE 11

### ISSUE THREAD

**Issue by jcheenatcode** [predixdesignsystem/px-dropdown#78]
Hello,

px-dropdown 4.5.4 & above does not work in IE 11. When we drop down the version to 4.2.2 which is the latest before 4.3(Polymer 2) everything works fine.

## Expected behavior and actual behavior:
px-dropdown should work in IE 11, but it doesn't work

## Steps to reproduce the problem:
Opening the code pen from the [px-dropdown](https://www.predix-ui.com/#/elements/px-dropdown) doesn't work

## Environment 
IE11
Windows 10

## Screenshots (_optional, but very helpful_):
IE 11 screenshot in code pen from the [px-dropdown](https://www.predix-ui.com/#/elements/px-dropdown) page.
![px-dropdown_ie11_doesnt_work](https://user-images.githubusercontent.com/23624174/36734626-b0e9bd0e-1b99-11e8-8a4d-51b5ce37b30d.png)

Chrome screenshot in code pen from the [px-dropdown](https://www.predix-ui.com/#/elements/px-dropdown) page.
![px-dropdown_chrome_works](https://user-images.githubusercontent.com/23624174/36734676-d8eff61a-1b99-11e8-9ba6-e8f714c5ba13.png)

## Code examples help us better understand the issue
Please use the code pen from the [px-dropdown](https://www.predix-ui.com/#/elements/px-dropdown) page.

**Comment by randyaskin** [comment]
I'm not sure why the CodePen is broken (something to do with polyfills I assume) but the component itself should be working fine in IE11, I spent the better part of yesterday trying to solve a display issue with the latest version of dropdown. The only other thing I can think of is that polymer serve/build do transpilation for us, but dropdown is not one of our components that uses ES6 anyway...
