### ISSUE TITLE
px-dropdown-selection-changed event excludes HTML data attributes

### ISSUE THREAD

**Issue by Alanxu5** [predixdesignsystem/px-dropdown#81]
## Expected behavior and actual behavior:
I have HTML data attributes associated with a px-dropdown so I expect when the px-dropdown-selection-changed event is fired and consumed the data attributes I set for the px-dropdown should be included in the event (e.srcElement.dataset). However, now the dataset is empty.  

## Steps to reproduce the problem:
Create dropdown with px-dropdown and use the HTML data attribute. Add an event listener to px-dropdown-selection-changed. Consume event and see that the data attribute is empty.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-dropdown: "^4.0.0", Chrome 64, MacOS Sierra

## Screenshots (_optional, but very helpful_):
![image](https://user-images.githubusercontent.com/7967314/37437371-1307820c-27aa-11e8-9dc5-35c0ff098458.png)

**Comment by randyaskin** [comment]
`srcElement` is a non-standard feature introduced by Internet Explorer, you should probably be using `target` instead (unless you're dealing with [event retargeting](https://www.polymer-project.org/2.0/docs/devguide/events#retargeting) issues).

This CodePen shows examples with `srcElement` `target` and Polymer's `localTarget` - all three options work fine in Chrome, but `srcElement` throws an undefined console error in Firefox, which is probably similar to what you're seeing:
https://codepen.io/randyaskin/pen/vRKZVy?editors=1011

**Comment by Alanxu5** [comment]
Thanks @randyaskin! https://developer.mozilla.org/en-US/docs/Web/API/Event/srcElement was a good article I found talking about srcElement vs target.
