### ISSUE TITLE
Can't programmatically set selection without firing change event

### ISSUE THREAD

**Issue by leebickmtu** [predixdesignsystem/px-dropdown#83]
Since the 4.0 redesign when setting the dropdown `selected` property in code the `px-dropdown-selection-changed` event fires as a result.

This may be useful in some cases. But there are times where I only want the event in response to user selections. When setting the initial state of a form and such through code I don't want the event to fire and process the selection.

**Comment by sgoodrow** [comment]
You will need to check the state of your application when the event is fired and filter the event method's activity based on that state.

I believe this is preferable to the prior behavior where the event would not fire when the selection changed programmatically .
