### ISSUE TITLE
Dropdown should have a max width 2

### ISSUE THREAD

**Issue by samc27** [predixdesignsystem/px-dropdown#86]
Hi, this is to highlight an issue that was resolved a while back (https://github.com/predixdesignsystem/px-dropdown/issues/50), however still exists.

When one of the options in the dropdown is very long, it gets truncated within the dropdown menu (as it should).
![image](https://user-images.githubusercontent.com/3090199/44046944-e8097702-9f24-11e8-9a14-69e271976473.png)

However, if I select that option, the dropdown button takes on the length of that item making the entire menu very long.
![image](https://user-images.githubusercontent.com/3090199/44046950-ee1f6e62-9f24-11e8-8d08-c48ac919cdea.png)

**Comment by arongraham-ge** [comment]
Updated the max-width of dropdown-trigger to respect the --px-dropdown-min-width setting
