### ISSUE TITLE
triggerClicked error (cannot read property "open" of null, line 340 of px-dropdown.html

### ISSUE THREAD

**Issue by 3rdPedal** [predixdesignsystem/px-dropdown#90]
## Expected behavior and actual behavior:
- expected: to have dropdown open with list of array items that have been specified
- actual: dropdown does not open, produces error: (px-dropdown.html:340 Uncaught TypeError: Cannot read property 'open' of null)

## Steps to reproduce the problem:
-local development environment
-latest px-dropdown from bower

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
-px-dropdown version 3.1.1
-Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
-MAC OS on MacBook Pro 15
-Bower, NodeJS, gulp

**Comment by 3rdPedal** [comment]
FYI: I'm a new developer and this is my first time reporting an issue.  Please coach me up if I'm not doing this right....thanks!

**Comment by sgoodrow** [comment]
Can you provide a code sample or code-pen that reproduces this issue?

**Comment by arongraham-ge** [comment]
@3rdPedal can you please send code example. We are unable to duplicate this issue in latest release v4.7.9.
